### ISSUE TITLE
All screenshots fail to upload in Mojave

### ISSUE THREAD

**Issue by jkhco** [bluegill/katana#19]
In Mojave, screenshots attempted uploading using any of the services fail. Katana seems to have all permissions required within Security and Privacy settings.

## Steps to Reproduce

1. Install Katana in macOS Mojave.
2. Select any service for upload.
3. Attempt to take a screenshot.

## Context (Environment)
Running macOS Mojave 10.14 Beta (18A353d) w/ Katana version v1.4.1

*(I realize that Mojave is likely an unsupported environment for Katana, but I thought I'd give a heads up, I especially would like to use Katana still while apart of the beta program if possible).*

**Comment by bluegill** [comment]
Looking into this issue now. It should be resolved in a future Katana update.
