### ISSUE TITLE
Add support for custom APIs like ShareX

### ISSUE THREAD

**Issue by RedEyeComputing** [bluegill/katana#7]
I'm not expecting this to be easy, but this program seems to be inspired by ShareX and I was wondering if it would be possible to add a feature like this one: http://i.redeyecomputing.com/7X1g0l.png Not sure what the chances are but thought I would suggest it, I would defiantly use this program full time if it was added.

**Comment by bluegill** [comment]
It wouldn't be difficult to implement custom API support. I will resume development after the Holidays.

Cheers.

**Comment by bluegill** [comment]
Basic functionality of this feature has been implemented. Issue closed.
